import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Disable all rules
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
      "no-debugger": "off",
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-empty": "off",
      "no-var": "off",
      "prefer-const": "off",
      "no-multiple-empty-lines": "off",
      "no-trailing-spaces": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-tabs": "off",
      "indent": "off",
      "semi": "off",
      "quotes": "off",
      "comma-dangle": "off",
      "object-curly-spacing": "off",
      "array-bracket-spacing": "off",
      "arrow-parens": "off",
      "arrow-spacing": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "camelcase": "off",
      "comma-spacing": "off",
      "comma-style": "off",
      "computed-property-spacing": "off",
      "consistent-this": "off",
      "eol-last": "off",
      "func-call-spacing": "off",
      "func-name-matching": "off",
      "func-names": "off",
      "func-style": "off",
      "id-blacklist": "off",
      "id-length": "off",
      "id-match": "off",
      "implicit-arrow-linebreak": "off",
      "jsx-quotes": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "line-comment-position": "off",
      "linebreak-style": "off",
      "lines-around-comment": "off",
      "lines-between-class-members": "off",
      "max-depth": "off",
      "max-len": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements": "off",
      "max-statements-per-line": "off",
      "multiline-comment-style": "off",
      "multiline-ternary": "off",
      "new-cap": "off",
      "new-parens": "off",
      "newline-after-var": "off",
      "newline-before-return": "off",
      "newline-per-chained-call": "off",
      "no-array-constructor": "off",
      "no-bitwise": "off",
      "no-continue": "off",
      "no-inline-comments": "off",
      "no-lonely-if": "off",
      "no-multi-assign": "off",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new-object": "off",
      "no-plusplus": "off",
      "no-restricted-syntax": "off",
      "no-ternary": "off",
      "no-underscore-dangle": "off",
      "no-unneeded-ternary": "off",
      "no-whitespace-before-property": "off",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-property-newline": "off",
      "one-var": "off",
      "one-var-declaration-per-line": "off",
      "operator-assignment": "off",
      "operator-linebreak": "off",
      "padded-blocks": "off",
      "padding-line-between-statements": "off",
      "prefer-object-spread": "off",
      "quote-props": "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "switch-colon-spacing": "off",
      "template-tag-spacing": "off",
      "unicode-bom": "off",
      "wrap-regex": "off"
    },
  },
];

export default eslintConfig;