export const doctorsData = [
  {
    id: 'DOC-1001',
    name: 'Dr. Sarah Johnson',
    specialty: 'Family Medicine',
    gender: 'Female',
    phone_number: '(555) 123-4567',
    status: 'APPROVED',
    location: 'Main Clinic',
    education: 'Harvard Medical School',
    experience: '12 years',
    languages: ['English', 'Spanish'],
    bio: 'Dr. Johnson specializes in comprehensive family care with a focus on preventive medicine and chronic disease management.',
    lastConsultation: 'May 15, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1002',
    name: 'Dr. Michael Chen',
    specialty: 'Cardiology',
    gender: 'Male',
    phone_number: '(555) 234-5678',
    status: 'APPROVED',
    location: 'Specialty Center',
    education: 'Johns Hopkins University',
    experience: '15 years',
    languages: ['English', 'Mandarin'],
    bio: 'Dr. Chen is a board-certified cardiologist with expertise in interventional procedures and cardiovascular health maintenance.',
    lastConsultation: 'May 14, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1003',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrics',
    gender: 'Female',
    phone_number: '(555) 345-6789',
    status: 'PENDING',
    location: 'Children\'s Wing',
    education: 'Stanford Medical School',
    experience: '8 years',
    languages: ['English', 'Spanish', 'Portuguese'],
    bio: 'Dr. Rodriguez focuses on pediatric care from newborns to adolescents with a special interest in developmental pediatrics.',
    lastConsultation: 'May 1, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1004',
    name: 'Dr. James Wilson',
    specialty: 'Orthopedics',
    gender: 'Male',
    phone_number: '(555) 456-7890',
    status: 'APPROVED',
    location: 'Main Clinic',
    education: 'Yale School of Medicine',
    experience: '20 years',
    languages: ['English'],
    bio: 'Dr. Wilson specializes in sports medicine and joint replacements with minimally invasive surgical techniques.',
    lastConsultation: 'May 16, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1005',
    name: 'Dr. Aisha Patel',
    specialty: 'Dermatology',
    gender: 'Female',
    phone_number: '(555) 567-8901',
    status: 'REJECTED',
    location: 'Specialty Center',
    education: 'University of California',
    experience: '10 years',
    languages: ['English', 'Hindi', 'Gujarati'],
    bio: 'Dr. Patel practices medical and cosmetic dermatology with expertise in skin cancer detection and treatment.',
    lastConsultation: 'May 12, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1006',
    name: 'Dr. Robert Kim',
    specialty: 'Neurology',
    gender: 'Male',
    phone_number: '(555) 678-9012',
    status: 'PENDING',
    location: 'Research Department',
    education: 'Columbia University',
    experience: '18 years',
    languages: ['English', 'Korean'],
    bio: 'Dr. Kim is a neurologist specializing in movement disorders and neurodegenerative diseases.',
    lastConsultation: 'Apr 30, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1007',
    name: 'Dr. Sofia Martinez',
    specialty: 'Psychiatry',
    gender: 'Female',
    phone_number: '(555) 789-0123',
    status: 'APPROVED',
    location: 'Mental Health Wing',
    education: 'NYU School of Medicine',
    experience: '9 years',
    languages: ['English', 'Spanish'],
    bio: 'Dr. Martinez focuses on adult psychiatry with expertise in anxiety disorders, depression, and PTSD.',
    lastConsultation: 'May 13, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1008',
    name: 'Dr. David Thompson',
    specialty: 'Gastroenterology',
    gender: 'Male',
    phone_number: '(555) 890-1234',
    status: 'APPROVED',
    location: 'Main Clinic',
    education: 'Mayo Medical School',
    experience: '14 years',
    languages: ['English'],
    bio: 'Dr. Thompson specializes in digestive health and advanced endoscopic procedures.',
    lastConsultation: 'May 16, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1009',
    name: 'Dr. Anna Ivanova',
    specialty: 'Ophthalmology',
    gender: 'Female',
    phone_number: '(555) 901-2345',
    status: 'REJECTED',
    location: 'Vision Center',
    education: 'Duke University',
    experience: '16 years',
    languages: ['English', 'Russian'],
    bio: 'Dr. Ivanova specializes in cataract surgery and comprehensive eye care for patients of all ages.',
    lastConsultation: 'May 10, 2025',
    avatar: '/api/placeholder/40/40'
  },
  {
    id: 'DOC-1010',
    name: 'Dr. Thomas Nguyen',
    specialty: 'Endocrinology',
    gender: 'Male',
    phone_number: '(555) 012-3456',
    status: 'PENDING',
    location: 'Specialty Center',
    education: 'University of Chicago',
    experience: '7 years',
    languages: ['English', 'Vietnamese'],
    bio: 'Dr. Nguyen specializes in diabetes management, thyroid disorders, and other hormonal conditions.',
    lastConsultation: 'N/A',
    avatar: '/api/placeholder/40/40'
  }
];
